/********************************************************************
* AIDADictionary.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error AIDADictionary.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableAIDADictionary();
extern void G__cpp_setup_inheritanceAIDADictionary();
extern void G__cpp_setup_typetableAIDADictionary();
extern void G__cpp_setup_memvarAIDADictionary();
extern void G__cpp_setup_globalAIDADictionary();
extern void G__cpp_setup_memfuncAIDADictionary();
extern void G__cpp_setup_funcAIDADictionary();
extern void G__set_cpp_environmentAIDADictionary();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "AIDA.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__AIDADictionaryLN_TClass;
extern G__linked_taginfo G__AIDADictionaryLN_TBuffer;
extern G__linked_taginfo G__AIDADictionaryLN_TMemberInspector;
extern G__linked_taginfo G__AIDADictionaryLN_TObject;
extern G__linked_taginfo G__AIDADictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__AIDADictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__AIDADictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__AIDADictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__AIDADictionaryLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__AIDADictionaryLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__AIDADictionaryLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__AIDADictionaryLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__AIDADictionaryLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__AIDADictionaryLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__AIDADictionaryLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__AIDADictionaryLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__AIDADictionaryLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__AIDADictionaryLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__AIDADictionaryLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__AIDADictionaryLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__AIDADictionaryLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__AIDADictionaryLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__AIDADictionaryLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__AIDADictionaryLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__AIDADictionaryLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__AIDADictionaryLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__AIDADictionaryLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__AIDADictionaryLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__AIDADictionaryLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__AIDADictionaryLN_TVector3;
extern G__linked_taginfo G__AIDADictionaryLN_AIDAHit;
extern G__linked_taginfo G__AIDADictionaryLN_AIDACluster;
extern G__linked_taginfo G__AIDADictionaryLN_AIDA;
extern G__linked_taginfo G__AIDADictionaryLN_vectorlEAIDAHitmUcOallocatorlEAIDAHitmUgRsPgR;
extern G__linked_taginfo G__AIDADictionaryLN_reverse_iteratorlEvectorlEAIDAHitmUcOallocatorlEAIDAHitmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__AIDADictionaryLN_vectorlEAIDAClustermUcOallocatorlEAIDAClustermUgRsPgR;
extern G__linked_taginfo G__AIDADictionaryLN_reverse_iteratorlEvectorlEAIDAClustermUcOallocatorlEAIDAClustermUgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
