/********************************************************************
* BeamDictionary.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error BeamDictionary.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableBeamDictionary();
extern void G__cpp_setup_inheritanceBeamDictionary();
extern void G__cpp_setup_typetableBeamDictionary();
extern void G__cpp_setup_memvarBeamDictionary();
extern void G__cpp_setup_globalBeamDictionary();
extern void G__cpp_setup_memfuncBeamDictionary();
extern void G__cpp_setup_funcBeamDictionary();
extern void G__set_cpp_environmentBeamDictionary();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "Beam.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__BeamDictionaryLN_TClass;
extern G__linked_taginfo G__BeamDictionaryLN_TBuffer;
extern G__linked_taginfo G__BeamDictionaryLN_TMemberInspector;
extern G__linked_taginfo G__BeamDictionaryLN_TObject;
extern G__linked_taginfo G__BeamDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__BeamDictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BeamDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__BeamDictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BeamDictionaryLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__BeamDictionaryLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__BeamDictionaryLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__BeamDictionaryLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__BeamDictionaryLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__BeamDictionaryLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__BeamDictionaryLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__BeamDictionaryLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__BeamDictionaryLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__BeamDictionaryLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__BeamDictionaryLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__BeamDictionaryLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__BeamDictionaryLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__BeamDictionaryLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__BeamDictionaryLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__BeamDictionaryLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__BeamDictionaryLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__BeamDictionaryLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__BeamDictionaryLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__BeamDictionaryLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__BeamDictionaryLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__BeamDictionaryLN_Beam;

/* STUB derived class for protected member access */
