/********************************************************************
* BELENDictionary.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error BELENDictionary.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableBELENDictionary();
extern void G__cpp_setup_inheritanceBELENDictionary();
extern void G__cpp_setup_typetableBELENDictionary();
extern void G__cpp_setup_memvarBELENDictionary();
extern void G__cpp_setup_globalBELENDictionary();
extern void G__cpp_setup_memfuncBELENDictionary();
extern void G__cpp_setup_funcBELENDictionary();
extern void G__set_cpp_environmentBELENDictionary();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "BELEN.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__BELENDictionaryLN_TClass;
extern G__linked_taginfo G__BELENDictionaryLN_TBuffer;
extern G__linked_taginfo G__BELENDictionaryLN_TMemberInspector;
extern G__linked_taginfo G__BELENDictionaryLN_TObject;
extern G__linked_taginfo G__BELENDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__BELENDictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BELENDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__BELENDictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BELENDictionaryLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__BELENDictionaryLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__BELENDictionaryLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__BELENDictionaryLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__BELENDictionaryLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__BELENDictionaryLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__BELENDictionaryLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__BELENDictionaryLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__BELENDictionaryLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__BELENDictionaryLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__BELENDictionaryLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__BELENDictionaryLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__BELENDictionaryLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__BELENDictionaryLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__BELENDictionaryLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__BELENDictionaryLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__BELENDictionaryLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__BELENDictionaryLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__BELENDictionaryLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__BELENDictionaryLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__BELENDictionaryLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__BELENDictionaryLN_TVector3;
extern G__linked_taginfo G__BELENDictionaryLN_BELENHit;
extern G__linked_taginfo G__BELENDictionaryLN_BELEN;
extern G__linked_taginfo G__BELENDictionaryLN_vectorlEBELENHitmUcOallocatorlEBELENHitmUgRsPgR;
extern G__linked_taginfo G__BELENDictionaryLN_reverse_iteratorlEvectorlEBELENHitmUcOallocatorlEBELENHitmUgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
