//
// File generated by rootcint at Sun Oct  2 19:49:06 2016

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME BELENDictionary
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "BELENDictionary.h"

#include "TCollectionProxyInfo.h"
#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void BELENHit_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_BELENHit(void *p = 0);
   static void *newArray_BELENHit(Long_t size, void *p);
   static void delete_BELENHit(void *p);
   static void deleteArray_BELENHit(void *p);
   static void destruct_BELENHit(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::BELENHit*)
   {
      ::BELENHit *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::BELENHit >(0);
      static ::ROOT::TGenericClassInfo 
         instance("BELENHit", ::BELENHit::Class_Version(), "./BELEN.h", 16,
                  typeid(::BELENHit), ::ROOT::DefineBehavior(ptr, ptr),
                  &::BELENHit::Dictionary, isa_proxy, 4,
                  sizeof(::BELENHit) );
      instance.SetNew(&new_BELENHit);
      instance.SetNewArray(&newArray_BELENHit);
      instance.SetDelete(&delete_BELENHit);
      instance.SetDeleteArray(&deleteArray_BELENHit);
      instance.SetDestructor(&destruct_BELENHit);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::BELENHit*)
   {
      return GenerateInitInstanceLocal((::BELENHit*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::BELENHit*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

namespace ROOTDict {
   void BELEN_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_BELEN(void *p = 0);
   static void *newArray_BELEN(Long_t size, void *p);
   static void delete_BELEN(void *p);
   static void deleteArray_BELEN(void *p);
   static void destruct_BELEN(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::BELEN*)
   {
      ::BELEN *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::BELEN >(0);
      static ::ROOT::TGenericClassInfo 
         instance("BELEN", ::BELEN::Class_Version(), "./BELEN.h", 108,
                  typeid(::BELEN), ::ROOT::DefineBehavior(ptr, ptr),
                  &::BELEN::Dictionary, isa_proxy, 4,
                  sizeof(::BELEN) );
      instance.SetNew(&new_BELEN);
      instance.SetNewArray(&newArray_BELEN);
      instance.SetDelete(&delete_BELEN);
      instance.SetDeleteArray(&deleteArray_BELEN);
      instance.SetDestructor(&destruct_BELEN);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::BELEN*)
   {
      return GenerateInitInstanceLocal((::BELEN*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::BELEN*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

//______________________________________________________________________________
atomic_TClass_ptr BELENHit::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *BELENHit::Class_Name()
{
   return "BELENHit";
}

//______________________________________________________________________________
const char *BELENHit::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::BELENHit*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int BELENHit::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::BELENHit*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void BELENHit::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::BELENHit*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *BELENHit::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::BELENHit*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
atomic_TClass_ptr BELEN::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *BELEN::Class_Name()
{
   return "BELEN";
}

//______________________________________________________________________________
const char *BELEN::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::BELEN*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int BELEN::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::BELEN*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void BELEN::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::BELEN*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *BELEN::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::BELEN*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void BELENHit::Streamer(TBuffer &R__b)
{
   // Stream an object of class BELENHit.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(BELENHit::Class(),this);
   } else {
      R__b.WriteClassBuffer(BELENHit::Class(),this);
   }
}

//______________________________________________________________________________
void BELENHit::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class BELENHit.
      TClass *R__cl = ::BELENHit::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fhitsadded", &fhitsadded);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fhe3pos", &fhe3pos);
      R__insp.InspectMember(fhe3pos, "fhe3pos.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fid", &fid);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fadc", &fadc);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fen", &fen);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fts", &fts);
      TObject::ShowMembers(R__insp);
}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_BELENHit(void *p) {
      return  p ? new(p) ::BELENHit : new ::BELENHit;
   }
   static void *newArray_BELENHit(Long_t nElements, void *p) {
      return p ? new(p) ::BELENHit[nElements] : new ::BELENHit[nElements];
   }
   // Wrapper around operator delete
   static void delete_BELENHit(void *p) {
      delete ((::BELENHit*)p);
   }
   static void deleteArray_BELENHit(void *p) {
      delete [] ((::BELENHit*)p);
   }
   static void destruct_BELENHit(void *p) {
      typedef ::BELENHit current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::BELENHit

//______________________________________________________________________________
void BELEN::Streamer(TBuffer &R__b)
{
   // Stream an object of class BELEN.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(BELEN::Class(),this);
   } else {
      R__b.WriteClassBuffer(BELEN::Class(),this);
   }
}

//______________________________________________________________________________
void BELEN::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class BELEN.
      TClass *R__cl = ::BELEN::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fmult", &fmult);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fbelents", &fbelents);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fhits", (void*)&fhits);
      R__insp.InspectMember("vector<BELENHit*>", (void*)&fhits, "fhits.", false);
      TObject::ShowMembers(R__insp);
}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_BELEN(void *p) {
      return  p ? new(p) ::BELEN : new ::BELEN;
   }
   static void *newArray_BELEN(Long_t nElements, void *p) {
      return p ? new(p) ::BELEN[nElements] : new ::BELEN[nElements];
   }
   // Wrapper around operator delete
   static void delete_BELEN(void *p) {
      delete ((::BELEN*)p);
   }
   static void deleteArray_BELEN(void *p) {
      delete [] ((::BELEN*)p);
   }
   static void destruct_BELEN(void *p) {
      typedef ::BELEN current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::BELEN

namespace ROOTDict {
   void vectorlEBELENHitmUgR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlEBELENHitmUgR_Dictionary();
   static void *new_vectorlEBELENHitmUgR(void *p = 0);
   static void *newArray_vectorlEBELENHitmUgR(Long_t size, void *p);
   static void delete_vectorlEBELENHitmUgR(void *p);
   static void deleteArray_vectorlEBELENHitmUgR(void *p);
   static void destruct_vectorlEBELENHitmUgR(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const vector<BELENHit*>*)
   {
      vector<BELENHit*> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<BELENHit*>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<BELENHit*>", -2, "/home/phong/root/cint/cint/lib/prec_stl/vector", 49,
                  typeid(vector<BELENHit*>), ::ROOT::DefineBehavior(ptr, ptr),
                  0, &vectorlEBELENHitmUgR_Dictionary, isa_proxy, 0,
                  sizeof(vector<BELENHit*>) );
      instance.SetNew(&new_vectorlEBELENHitmUgR);
      instance.SetNewArray(&newArray_vectorlEBELENHitmUgR);
      instance.SetDelete(&delete_vectorlEBELENHitmUgR);
      instance.SetDeleteArray(&deleteArray_vectorlEBELENHitmUgR);
      instance.SetDestructor(&destruct_vectorlEBELENHitmUgR);
      instance.AdoptCollectionProxyInfo( ::ROOT::TCollectionProxyInfo::Generate( ::ROOT::TCollectionProxyInfo::Pushback< vector<BELENHit*> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<BELENHit*>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEBELENHitmUgR_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const vector<BELENHit*>*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_vectorlEBELENHitmUgR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<BELENHit*> : new vector<BELENHit*>;
   }
   static void *newArray_vectorlEBELENHitmUgR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<BELENHit*>[nElements] : new vector<BELENHit*>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlEBELENHitmUgR(void *p) {
      delete ((vector<BELENHit*>*)p);
   }
   static void deleteArray_vectorlEBELENHitmUgR(void *p) {
      delete [] ((vector<BELENHit*>*)p);
   }
   static void destruct_vectorlEBELENHitmUgR(void *p) {
      typedef vector<BELENHit*> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class vector<BELENHit*>

/********************************************************
* BELENDictionary.cpp
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableBELENDictionary();

extern "C" void G__set_cpp_environmentBELENDictionary() {
  G__cpp_reset_tagtableBELENDictionary();
}
#include <new>
extern "C" int G__cpp_dllrevBELENDictionary() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* BELENHit */
static int G__BELENDictionary_221_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   BELENHit* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new BELENHit[n];
     } else {
       p = new((void*) gvp) BELENHit[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new BELENHit;
     } else {
       p = new((void*) gvp) BELENHit;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__BELENDictionaryLN_BELENHit));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BELENDictionary_221_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   BELENHit* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 8
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new BELENHit(
(Double_t) G__double(libp->para[0]), (Double_t) G__double(libp->para[1])
, (Double_t) G__double(libp->para[2]), (short) G__int(libp->para[3])
, (unsigned long long) G__ULonglong(libp->para[4]), (int) G__int(libp->para[5])
, (int) G__int(libp->para[6]), (unsigned short) G__int(libp->para[7]));
   } else {
     p = new((void*) gvp) BELENHit(
(Double_t) G__double(libp->para[0]), (Double_t) G__double(libp->para[1])
, (Double_t) G__double(libp->para[2]), (short) G__int(libp->para[3])
, (unsigned long long) G__ULonglong(libp->para[4]), (int) G__int(libp->para[5])
, (int) G__int(libp->para[6]), (unsigned short) G__int(libp->para[7]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__BELENDictionaryLN_BELENHit));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BELENDictionary_221_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BELENHit*) G__getstructoffset())->SetEnergy((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BELENDictionary_221_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BELENHit*) G__getstructoffset())->SetADC((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BELENDictionary_221_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BELENHit*) G__getstructoffset())->SetID((short) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BELENDictionary_221_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BELENHit*) G__getstructoffset())->SetTimestamp((unsigned long long) G__ULonglong(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BELENDictionary_221_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BELENHit*) G__getstructoffset())->SetPos((Double_t) G__double(libp->para[0]), (Double_t) G__double(libp->para[1])
, (Double_t) G__double(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BELENDictionary_221_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BELENHit*) G__getstructoffset())->SetHitsAdded((unsigned short) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BELENDictionary_221_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) ((BELENHit*) G__getstructoffset())->GetID());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BELENDictionary_221_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((BELENHit*) G__getstructoffset())->GetEnergy());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BELENDictionary_221_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letULonglong(result7, 109, (G__uint64) ((BELENHit*) G__getstructoffset())->GetTimestamp());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BELENDictionary_221_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((BELENHit*) G__getstructoffset())->GetADC());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BELENDictionary_221_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TVector3* pobj;
         TVector3 xobj = ((BELENHit*) G__getstructoffset())->GetPosition();
         pobj = new TVector3(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BELENDictionary_221_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 114, (long) ((BELENHit*) G__getstructoffset())->GetHitsAdded());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BELENDictionary_221_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BELENHit*) G__getstructoffset())->Clear();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BELENDictionary_221_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) BELENHit::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BELENDictionary_221_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) BELENHit::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BELENDictionary_221_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) BELENHit::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BELENDictionary_221_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      BELENHit::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BELENDictionary_221_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BELENHit*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BELENDictionary_221_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) BELENHit::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BELENDictionary_221_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) BELENHit::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BELENDictionary_221_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) BELENHit::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BELENDictionary_221_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) BELENHit::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__BELENDictionary_221_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   BELENHit* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new BELENHit(*(BELENHit*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__BELENDictionaryLN_BELENHit));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef BELENHit G__TBELENHit;
static int G__BELENDictionary_221_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (BELENHit*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((BELENHit*) (soff+(sizeof(BELENHit)*i)))->~G__TBELENHit();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (BELENHit*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((BELENHit*) (soff))->~G__TBELENHit();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__BELENDictionary_221_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   BELENHit* dest = (BELENHit*) G__getstructoffset();
   *dest = *(BELENHit*) libp->para[0].ref;
   const BELENHit& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* BELEN */
static int G__BELENDictionary_222_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   BELEN* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new BELEN[n];
     } else {
       p = new((void*) gvp) BELEN[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new BELEN;
     } else {
       p = new((void*) gvp) BELEN;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__BELENDictionaryLN_BELEN));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BELENDictionary_222_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BELEN*) G__getstructoffset())->Clear();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BELENDictionary_222_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BELEN*) G__getstructoffset())->SetTimestamp((unsigned long long) G__ULonglong(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BELENDictionary_222_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BELEN*) G__getstructoffset())->SetMult((unsigned short) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BELENDictionary_222_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BELEN*) G__getstructoffset())->AddHits(*((vector<BELENHit*>*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BELENDictionary_222_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BELEN*) G__getstructoffset())->AddHit((BELENHit*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BELENDictionary_222_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BELEN*) G__getstructoffset())->SetHits(*((vector<BELENHit*>*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BELENDictionary_222_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letULonglong(result7, 109, (G__uint64) ((BELEN*) G__getstructoffset())->GetTimestamp());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BELENDictionary_222_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 114, (long) ((BELEN*) G__getstructoffset())->GetMult());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BELENDictionary_222_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<BELENHit*>* pobj;
         vector<BELENHit*> xobj = ((BELEN*) G__getstructoffset())->GetHits();
         pobj = new vector<BELENHit*>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BELENDictionary_222_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((BELEN*) G__getstructoffset())->GetHit((unsigned short) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BELENDictionary_222_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) BELEN::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BELENDictionary_222_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) BELEN::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BELENDictionary_222_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) BELEN::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BELENDictionary_222_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      BELEN::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BELENDictionary_222_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BELEN*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BELENDictionary_222_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) BELEN::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BELENDictionary_222_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) BELEN::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BELENDictionary_222_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) BELEN::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__BELENDictionary_222_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) BELEN::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__BELENDictionary_222_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   BELEN* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new BELEN(*(BELEN*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__BELENDictionaryLN_BELEN));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef BELEN G__TBELEN;
static int G__BELENDictionary_222_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (BELEN*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((BELEN*) (soff+(sizeof(BELEN)*i)))->~G__TBELEN();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (BELEN*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((BELEN*) (soff))->~G__TBELEN();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__BELENDictionary_222_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   BELEN* dest = (BELEN*) G__getstructoffset();
   *dest = *(BELEN*) libp->para[0].ref;
   const BELEN& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* BELENHit */

/* BELEN */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncBELENDictionary {
 public:
  G__Sizep2memfuncBELENDictionary(): p(&G__Sizep2memfuncBELENDictionary::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncBELENDictionary::*p)();
};

size_t G__get_sizep2memfuncBELENDictionary()
{
  G__Sizep2memfuncBELENDictionary a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceBELENDictionary() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__BELENDictionaryLN_BELENHit))) {
     BELENHit *G__Lderived;
     G__Lderived=(BELENHit*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__BELENDictionaryLN_BELENHit),G__get_linked_tagnum(&G__BELENDictionaryLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__BELENDictionaryLN_BELEN))) {
     BELEN *G__Lderived;
     G__Lderived=(BELEN*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__BELENDictionaryLN_BELEN),G__get_linked_tagnum(&G__BELENDictionaryLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableBELENDictionary() {

   /* Setting up typedef entry */
   G__search_typename2("Double_t",100,-1,0,-1);
   G__setnewtype(-1,"Double 8 bytes",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__BELENDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BELENDictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BELENDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BELENDictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BELENDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__BELENDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BELENDictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BELENDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BELENDictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BELENDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__BELENDictionaryLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__BELENDictionaryLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__BELENDictionaryLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__BELENDictionaryLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Float_t>",117,G__get_linked_tagnum(&G__BELENDictionaryLN_TMatrixTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Float_t>",117,G__get_linked_tagnum(&G__BELENDictionaryLN_TMatrixTRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Float_t>",117,G__get_linked_tagnum(&G__BELENDictionaryLN_TMatrixTColumn_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Float_t>",117,G__get_linked_tagnum(&G__BELENDictionaryLN_TMatrixTDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Float_t>",117,G__get_linked_tagnum(&G__BELENDictionaryLN_TMatrixTFlat_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Float_t>",117,G__get_linked_tagnum(&G__BELENDictionaryLN_TMatrixTSub_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Float_t>",117,G__get_linked_tagnum(&G__BELENDictionaryLN_TMatrixTSparseRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Float_t>",117,G__get_linked_tagnum(&G__BELENDictionaryLN_TMatrixTSparseDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Float_t>",117,G__get_linked_tagnum(&G__BELENDictionaryLN_TMatrixTRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Float_t>",117,G__get_linked_tagnum(&G__BELENDictionaryLN_TMatrixTColumnlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Float_t>",117,G__get_linked_tagnum(&G__BELENDictionaryLN_TMatrixTDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Float_t>",117,G__get_linked_tagnum(&G__BELENDictionaryLN_TMatrixTFlatlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Float_t>",117,G__get_linked_tagnum(&G__BELENDictionaryLN_TMatrixTSublEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Float_t>",117,G__get_linked_tagnum(&G__BELENDictionaryLN_TMatrixTSparseRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Float_t>",117,G__get_linked_tagnum(&G__BELENDictionaryLN_TMatrixTSparseDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Float_t>",117,G__get_linked_tagnum(&G__BELENDictionaryLN_TElementActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Float_t>",117,G__get_linked_tagnum(&G__BELENDictionaryLN_TElementPosActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<BELENHit*>",117,G__get_linked_tagnum(&G__BELENDictionaryLN_vectorlEBELENHitmUcOallocatorlEBELENHitmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__BELENDictionaryLN_reverse_iteratorlEvectorlEBELENHitmUcOallocatorlEBELENHitmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BELENDictionaryLN_vectorlEBELENHitmUcOallocatorlEBELENHitmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__BELENDictionaryLN_reverse_iteratorlEvectorlEBELENHitmUcOallocatorlEBELENHitmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__BELENDictionaryLN_vectorlEBELENHitmUcOallocatorlEBELENHitmUgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* BELENHit */
static void G__setup_memvarBELENHit(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__BELENDictionaryLN_BELENHit));
   { BELENHit *p; p=(BELENHit*)0x1000; if (p) { }
   G__memvar_setup((void*)0,114,0,0,-1,-1,-1,2,"fhitsadded=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BELENDictionaryLN_TVector3),-1,-1,2,"fhe3pos=",0,(char*)NULL);
   G__memvar_setup((void*)0,115,0,0,-1,-1,-1,2,"fid=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,2,"fadc=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"fen=",0,(char*)NULL);
   G__memvar_setup((void*)0,109,0,0,-1,-1,-1,2,"fts=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__BELENDictionaryLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* BELEN */
static void G__setup_memvarBELEN(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__BELENDictionaryLN_BELEN));
   { BELEN *p; p=(BELEN*)0x1000; if (p) { }
   G__memvar_setup((void*)0,114,0,0,-1,-1,-1,2,"fmult=",0,(char*)NULL);
   G__memvar_setup((void*)0,109,0,0,-1,-1,-1,2,"fbelents=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__BELENDictionaryLN_vectorlEBELENHitmUcOallocatorlEBELENHitmUgRsPgR),G__defined_typename("vector<BELENHit*>"),-1,2,"fhits=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__BELENDictionaryLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarBELENDictionary() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncBELENHit(void) {
   /* BELENHit */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__BELENDictionaryLN_BELENHit));
   G__memfunc_setup("BELENHit",651,G__BELENDictionary_221_0_1, 105, G__get_linked_tagnum(&G__BELENDictionaryLN_BELENHit), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("BELENHit",651,G__BELENDictionary_221_0_2, 105, G__get_linked_tagnum(&G__BELENDictionaryLN_BELENHit), -1, 0, 8, 1, 1, 0, 
"d - 'Double_t' 0 - posx d - 'Double_t' 0 - posy "
"d - 'Double_t' 0 - posz s - - 0 - id "
"m - - 0 - ts i - - 0 - adc "
"i - - 0 - en r - - 0 - hitsadded", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetEnergy",918,G__BELENDictionary_221_0_3, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - energy", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetADC",500,G__BELENDictionary_221_0_4, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - adc", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetID",441,G__BELENDictionary_221_0_5, 121, -1, -1, 0, 1, 1, 1, 0, "s - - 0 - id", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetTimestamp",1248,G__BELENDictionary_221_0_6, 121, -1, -1, 0, 1, 1, 1, 0, "m - - 0 - ts", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetPos",606,G__BELENDictionary_221_0_7, 121, -1, -1, 0, 3, 1, 1, 0, 
"d - 'Double_t' 0 - x d - 'Double_t' 0 - y "
"d - 'Double_t' 0 - z", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetHitsAdded",1174,G__BELENDictionary_221_0_8, 121, -1, -1, 0, 1, 1, 1, 0, "r - - 0 - hitsadded", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetID",429,G__BELENDictionary_221_0_9, 115, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetEnergy",906,G__BELENDictionary_221_0_10, 100, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTimestamp",1236,G__BELENDictionary_221_0_11, 109, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetADC",488,G__BELENDictionary_221_0_12, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPosition",1141,G__BELENDictionary_221_0_13, 117, G__get_linked_tagnum(&G__BELENDictionaryLN_TVector3), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetHitsAdded",1162,G__BELENDictionary_221_0_14, 114, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Clear",487,G__BELENDictionary_221_0_15, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Print",525,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 8, "C - 'Option_t' 10 '\"\"' option", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Class",502,G__BELENDictionary_221_0_17, 85, G__get_linked_tagnum(&G__BELENDictionaryLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&BELENHit::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__BELENDictionary_221_0_18, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&BELENHit::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__BELENDictionary_221_0_19, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&BELENHit::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__BELENDictionary_221_0_20, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&BELENHit::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__BELENDictionaryLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__BELENDictionary_221_0_24, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__BELENDictionary_221_0_25, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&BELENHit::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__BELENDictionary_221_0_26, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&BELENHit::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__BELENDictionary_221_0_27, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&BELENHit::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__BELENDictionary_221_0_28, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&BELENHit::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("BELENHit", 651, G__BELENDictionary_221_0_29, (int) ('i'), G__get_linked_tagnum(&G__BELENDictionaryLN_BELENHit), -1, 0, 1, 1, 1, 0, "u 'BELENHit' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~BELENHit", 777, G__BELENDictionary_221_0_30, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__BELENDictionary_221_0_31, (int) ('u'), G__get_linked_tagnum(&G__BELENDictionaryLN_BELENHit), -1, 1, 1, 1, 1, 0, "u 'BELENHit' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncBELEN(void) {
   /* BELEN */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__BELENDictionaryLN_BELEN));
   G__memfunc_setup("BELEN",358,G__BELENDictionary_222_0_1, 105, G__get_linked_tagnum(&G__BELENDictionaryLN_BELEN), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Clear",487,G__BELENDictionary_222_0_2, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetTimestamp",1248,G__BELENDictionary_222_0_3, 121, -1, -1, 0, 1, 1, 1, 0, "m - - 0 - ts", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetMult",718,G__BELENDictionary_222_0_4, 121, -1, -1, 0, 1, 1, 1, 0, "r - - 0 - mult", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("AddHits",673,G__BELENDictionary_222_0_5, 121, -1, -1, 0, 1, 1, 1, 0, "u 'vector<BELENHit*,allocator<BELENHit*> >' 'vector<BELENHit*>' 0 - hits", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("AddHit",558,G__BELENDictionary_222_0_6, 121, -1, -1, 0, 1, 1, 1, 0, "U 'BELENHit' - 0 - hit", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetHits",708,G__BELENDictionary_222_0_7, 121, -1, -1, 0, 1, 1, 1, 0, "u 'vector<BELENHit*,allocator<BELENHit*> >' 'vector<BELENHit*>' 0 - hits", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTimestamp",1236,G__BELENDictionary_222_0_8, 109, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetMult",706,G__BELENDictionary_222_0_9, 114, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetHits",696,G__BELENDictionary_222_0_10, 117, G__get_linked_tagnum(&G__BELENDictionaryLN_vectorlEBELENHitmUcOallocatorlEBELENHitmUgRsPgR), G__defined_typename("vector<BELENHit*>"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetHit",581,G__BELENDictionary_222_0_11, 85, G__get_linked_tagnum(&G__BELENDictionaryLN_BELENHit), -1, 0, 1, 1, 1, 0, "r - - 0 - n", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Print",525,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 8, "C - 'Option_t' 10 '\"\"' option", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Class",502,G__BELENDictionary_222_0_13, 85, G__get_linked_tagnum(&G__BELENDictionaryLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&BELEN::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__BELENDictionary_222_0_14, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&BELEN::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__BELENDictionary_222_0_15, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&BELEN::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__BELENDictionary_222_0_16, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&BELEN::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__BELENDictionaryLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__BELENDictionary_222_0_20, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__BELENDictionary_222_0_21, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&BELEN::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__BELENDictionary_222_0_22, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&BELEN::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__BELENDictionary_222_0_23, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&BELEN::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__BELENDictionary_222_0_24, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&BELEN::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("BELEN", 358, G__BELENDictionary_222_0_25, (int) ('i'), G__get_linked_tagnum(&G__BELENDictionaryLN_BELEN), -1, 0, 1, 1, 1, 0, "u 'BELEN' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~BELEN", 484, G__BELENDictionary_222_0_26, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__BELENDictionary_222_0_27, (int) ('u'), G__get_linked_tagnum(&G__BELENDictionaryLN_BELEN), -1, 1, 1, 1, 1, 0, "u 'BELEN' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncBELENDictionary() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalBELENDictionary() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcBELENDictionary() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__BELENDictionaryLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__BELENDictionaryLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__BELENDictionaryLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__BELENDictionaryLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__BELENDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__BELENDictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BELENDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__BELENDictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__BELENDictionaryLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__BELENDictionaryLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__BELENDictionaryLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__BELENDictionaryLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__BELENDictionaryLN_TElementActionTlEfloatgR = { "TElementActionT<float>" , 99 , -1 };
G__linked_taginfo G__BELENDictionaryLN_TElementPosActionTlEfloatgR = { "TElementPosActionT<float>" , 99 , -1 };
G__linked_taginfo G__BELENDictionaryLN_TMatrixTlEfloatgR = { "TMatrixT<float>" , 99 , -1 };
G__linked_taginfo G__BELENDictionaryLN_TMatrixTRow_constlEfloatgR = { "TMatrixTRow_const<float>" , 99 , -1 };
G__linked_taginfo G__BELENDictionaryLN_TMatrixTRowlEfloatgR = { "TMatrixTRow<float>" , 99 , -1 };
G__linked_taginfo G__BELENDictionaryLN_TMatrixTDiag_constlEfloatgR = { "TMatrixTDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__BELENDictionaryLN_TMatrixTColumn_constlEfloatgR = { "TMatrixTColumn_const<float>" , 99 , -1 };
G__linked_taginfo G__BELENDictionaryLN_TMatrixTFlat_constlEfloatgR = { "TMatrixTFlat_const<float>" , 99 , -1 };
G__linked_taginfo G__BELENDictionaryLN_TMatrixTSub_constlEfloatgR = { "TMatrixTSub_const<float>" , 99 , -1 };
G__linked_taginfo G__BELENDictionaryLN_TMatrixTSparseRow_constlEfloatgR = { "TMatrixTSparseRow_const<float>" , 99 , -1 };
G__linked_taginfo G__BELENDictionaryLN_TMatrixTSparseDiag_constlEfloatgR = { "TMatrixTSparseDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__BELENDictionaryLN_TMatrixTColumnlEfloatgR = { "TMatrixTColumn<float>" , 99 , -1 };
G__linked_taginfo G__BELENDictionaryLN_TMatrixTDiaglEfloatgR = { "TMatrixTDiag<float>" , 99 , -1 };
G__linked_taginfo G__BELENDictionaryLN_TMatrixTFlatlEfloatgR = { "TMatrixTFlat<float>" , 99 , -1 };
G__linked_taginfo G__BELENDictionaryLN_TMatrixTSublEfloatgR = { "TMatrixTSub<float>" , 99 , -1 };
G__linked_taginfo G__BELENDictionaryLN_TMatrixTSparseRowlEfloatgR = { "TMatrixTSparseRow<float>" , 99 , -1 };
G__linked_taginfo G__BELENDictionaryLN_TMatrixTSparseDiaglEfloatgR = { "TMatrixTSparseDiag<float>" , 99 , -1 };
G__linked_taginfo G__BELENDictionaryLN_TVector3 = { "TVector3" , 99 , -1 };
G__linked_taginfo G__BELENDictionaryLN_BELENHit = { "BELENHit" , 99 , -1 };
G__linked_taginfo G__BELENDictionaryLN_BELEN = { "BELEN" , 99 , -1 };
G__linked_taginfo G__BELENDictionaryLN_vectorlEBELENHitmUcOallocatorlEBELENHitmUgRsPgR = { "vector<BELENHit*,allocator<BELENHit*> >" , 99 , -1 };
G__linked_taginfo G__BELENDictionaryLN_reverse_iteratorlEvectorlEBELENHitmUcOallocatorlEBELENHitmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<BELENHit*,allocator<BELENHit*> >::iterator>" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableBELENDictionary() {
  G__BELENDictionaryLN_TClass.tagnum = -1 ;
  G__BELENDictionaryLN_TBuffer.tagnum = -1 ;
  G__BELENDictionaryLN_TMemberInspector.tagnum = -1 ;
  G__BELENDictionaryLN_TObject.tagnum = -1 ;
  G__BELENDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__BELENDictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BELENDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__BELENDictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__BELENDictionaryLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__BELENDictionaryLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__BELENDictionaryLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__BELENDictionaryLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__BELENDictionaryLN_TElementActionTlEfloatgR.tagnum = -1 ;
  G__BELENDictionaryLN_TElementPosActionTlEfloatgR.tagnum = -1 ;
  G__BELENDictionaryLN_TMatrixTlEfloatgR.tagnum = -1 ;
  G__BELENDictionaryLN_TMatrixTRow_constlEfloatgR.tagnum = -1 ;
  G__BELENDictionaryLN_TMatrixTRowlEfloatgR.tagnum = -1 ;
  G__BELENDictionaryLN_TMatrixTDiag_constlEfloatgR.tagnum = -1 ;
  G__BELENDictionaryLN_TMatrixTColumn_constlEfloatgR.tagnum = -1 ;
  G__BELENDictionaryLN_TMatrixTFlat_constlEfloatgR.tagnum = -1 ;
  G__BELENDictionaryLN_TMatrixTSub_constlEfloatgR.tagnum = -1 ;
  G__BELENDictionaryLN_TMatrixTSparseRow_constlEfloatgR.tagnum = -1 ;
  G__BELENDictionaryLN_TMatrixTSparseDiag_constlEfloatgR.tagnum = -1 ;
  G__BELENDictionaryLN_TMatrixTColumnlEfloatgR.tagnum = -1 ;
  G__BELENDictionaryLN_TMatrixTDiaglEfloatgR.tagnum = -1 ;
  G__BELENDictionaryLN_TMatrixTFlatlEfloatgR.tagnum = -1 ;
  G__BELENDictionaryLN_TMatrixTSublEfloatgR.tagnum = -1 ;
  G__BELENDictionaryLN_TMatrixTSparseRowlEfloatgR.tagnum = -1 ;
  G__BELENDictionaryLN_TMatrixTSparseDiaglEfloatgR.tagnum = -1 ;
  G__BELENDictionaryLN_TVector3.tagnum = -1 ;
  G__BELENDictionaryLN_BELENHit.tagnum = -1 ;
  G__BELENDictionaryLN_BELEN.tagnum = -1 ;
  G__BELENDictionaryLN_vectorlEBELENHitmUcOallocatorlEBELENHitmUgRsPgR.tagnum = -1 ;
  G__BELENDictionaryLN_reverse_iteratorlEvectorlEBELENHitmUcOallocatorlEBELENHitmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableBELENDictionary() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__BELENDictionaryLN_TClass);
   G__get_linked_tagnum_fwd(&G__BELENDictionaryLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__BELENDictionaryLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__BELENDictionaryLN_TObject);
   G__get_linked_tagnum_fwd(&G__BELENDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__BELENDictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BELENDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__BELENDictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__BELENDictionaryLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__BELENDictionaryLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__BELENDictionaryLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__BELENDictionaryLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__BELENDictionaryLN_TElementActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__BELENDictionaryLN_TElementPosActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__BELENDictionaryLN_TMatrixTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__BELENDictionaryLN_TMatrixTRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__BELENDictionaryLN_TMatrixTRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__BELENDictionaryLN_TMatrixTDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__BELENDictionaryLN_TMatrixTColumn_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__BELENDictionaryLN_TMatrixTFlat_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__BELENDictionaryLN_TMatrixTSub_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__BELENDictionaryLN_TMatrixTSparseRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__BELENDictionaryLN_TMatrixTSparseDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__BELENDictionaryLN_TMatrixTColumnlEfloatgR);
   G__get_linked_tagnum_fwd(&G__BELENDictionaryLN_TMatrixTDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__BELENDictionaryLN_TMatrixTFlatlEfloatgR);
   G__get_linked_tagnum_fwd(&G__BELENDictionaryLN_TMatrixTSublEfloatgR);
   G__get_linked_tagnum_fwd(&G__BELENDictionaryLN_TMatrixTSparseRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__BELENDictionaryLN_TMatrixTSparseDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__BELENDictionaryLN_TVector3);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__BELENDictionaryLN_BELENHit),sizeof(BELENHit),-1,323840,(char*)NULL,G__setup_memvarBELENHit,G__setup_memfuncBELENHit);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__BELENDictionaryLN_BELEN),sizeof(BELEN),-1,291072,(char*)NULL,G__setup_memvarBELEN,G__setup_memfuncBELEN);
   G__get_linked_tagnum_fwd(&G__BELENDictionaryLN_vectorlEBELENHitmUcOallocatorlEBELENHitmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__BELENDictionaryLN_reverse_iteratorlEvectorlEBELENHitmUcOallocatorlEBELENHitmUgRsPgRcLcLiteratorgR);
}
extern "C" void G__cpp_setupBELENDictionary(void) {
  G__check_setup_version(30051515,"G__cpp_setupBELENDictionary()");
  G__set_cpp_environmentBELENDictionary();
  G__cpp_setup_tagtableBELENDictionary();

  G__cpp_setup_inheritanceBELENDictionary();

  G__cpp_setup_typetableBELENDictionary();

  G__cpp_setup_memvarBELENDictionary();

  G__cpp_setup_memfuncBELENDictionary();
  G__cpp_setup_globalBELENDictionary();
  G__cpp_setup_funcBELENDictionary();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncBELENDictionary();
  return;
}
class G__cpp_setup_initBELENDictionary {
  public:
    G__cpp_setup_initBELENDictionary() { G__add_setup_func("BELENDictionary",(G__incsetup)(&G__cpp_setupBELENDictionary)); G__call_setup_funcs(); }
   ~G__cpp_setup_initBELENDictionary() { G__remove_setup_func("BELENDictionary"); }
};
G__cpp_setup_initBELENDictionary G__cpp_setup_initializerBELENDictionary;

