/********************************************************************
* CloverDictionary.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error CloverDictionary.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableCloverDictionary();
extern void G__cpp_setup_inheritanceCloverDictionary();
extern void G__cpp_setup_typetableCloverDictionary();
extern void G__cpp_setup_memvarCloverDictionary();
extern void G__cpp_setup_globalCloverDictionary();
extern void G__cpp_setup_memfuncCloverDictionary();
extern void G__cpp_setup_funcCloverDictionary();
extern void G__set_cpp_environmentCloverDictionary();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "Clover.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__CloverDictionaryLN_TClass;
extern G__linked_taginfo G__CloverDictionaryLN_TBuffer;
extern G__linked_taginfo G__CloverDictionaryLN_TMemberInspector;
extern G__linked_taginfo G__CloverDictionaryLN_TObject;
extern G__linked_taginfo G__CloverDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__CloverDictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__CloverDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__CloverDictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__CloverDictionaryLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__CloverDictionaryLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__CloverDictionaryLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__CloverDictionaryLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__CloverDictionaryLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__CloverDictionaryLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__CloverDictionaryLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__CloverDictionaryLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__CloverDictionaryLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__CloverDictionaryLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__CloverDictionaryLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__CloverDictionaryLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__CloverDictionaryLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__CloverDictionaryLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__CloverDictionaryLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__CloverDictionaryLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__CloverDictionaryLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__CloverDictionaryLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__CloverDictionaryLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__CloverDictionaryLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__CloverDictionaryLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__CloverDictionaryLN_CloverHit;
extern G__linked_taginfo G__CloverDictionaryLN_Clover;
extern G__linked_taginfo G__CloverDictionaryLN_vectorlECloverHitmUcOallocatorlECloverHitmUgRsPgR;
extern G__linked_taginfo G__CloverDictionaryLN_reverse_iteratorlEvectorlECloverHitmUcOallocatorlECloverHitmUgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
